Changes for fetch= webboot to work with Wheezy.

diff --git a/live-boot-2/scripts/live b/live-boot-2/scripts/live
--- a/live-boot-2/scripts/live
+++ b/live-boot-2/scripts/live
@@ -573,6 +573,7 @@ copy_live_to ()
 	return 0
 }
 
+#saintless - this function is from live-boot-3:
 do_netsetup ()
 {
 	modprobe -q af_packet # For DHCP
@@ -580,93 +581,117 @@ do_netsetup ()
 	udevadm trigger
 	udevadm settle
 
-	if [ -z "${NETBOOT}" ] && [ -z "${FETCH}" ] && \
-	   [ -z "${HTTPFS}" ] && [ -z "${FTPFS}" ]
-	then
+	[ -n "$ETHDEV_TIMEOUT" ] || ETHDEV_TIMEOUT=15
+	echo "Using timeout of $ETHDEV_TIMEOUT seconds for network configuration."
 
-	# if ethdevice was not specified on the kernel command line
-	# make sure we try to get a working network configuration
-	# for *every* present network device (except for loopback of course)
-	if [ -z "$ETHDEVICE" ] ; then
-		echo "If you want to boot from a specific device use bootoption ethdevice=..."
-		for device in /sys/class/net/*; do
-			dev=${device##*/} ;
-			if [ "$dev" != "lo" ] ; then
-				ETHDEVICE="$ETHDEVICE $dev"
+	if [ -z "${NETBOOT}" ] && [ -z "${FETCH}" ] && [ -z "${HTTPFS}" ] && [ -z "${FTPFS}" ]
+	then
+		# See if we can select the device from BOOTIF
+		Device_from_bootif
+
+		# if ethdevice was not specified on the kernel command line
+		# make sure we try to get a working network configuration
+		# for *every* present network device (except for loopback of course)
+		if [ -z "$ETHDEVICE" ]
+		then
+			echo "If you want to boot from a specific device use bootoption ethdevice=..."
+			for device in /sys/class/net/*
+			do
+				dev=${device##*/}
+				if [ "$dev" != "lo" ]
+				then
+					ETHDEVICE="$ETHDEVICE $dev"
+				fi
+			done
+		fi
+
+		# split args of ethdevice=eth0,eth1 into "eth0 eth1"
+		for device in $(echo $ETHDEVICE | sed 's/,/ /g')
+		do
+			devlist="$devlist $device"
+		done
+
+		# this is tricky (and ugly) because ipconfig sometimes just hangs/runs into
+		# an endless loop; if execution fails give it two further tries, that's
+		# why we use '$devlist $devlist $devlist' for the other for loop
+		for dev in $devlist $devlist $devlist
+		do
+			echo "Executing ipconfig -t $ETHDEV_TIMEOUT $dev"
+			ipconfig -t "$ETHDEV_TIMEOUT" $dev | tee -a /netboot.config &
+			jobid=$!
+			sleep "$ETHDEV_TIMEOUT" ; sleep 1
+			if [ -r /proc/"$jobid"/status ]
+			then
+				echo "Killing job $jobid for device $dev as ipconfig ran into recursion..."
+				kill -9 $jobid
+			fi
+
+			# if configuration of device worked we should have an assigned
+			# IP address, if so let's use the device as $DEVICE for later usage.
+			# simple and primitive approach which seems to work fine
+			if ifconfig $dev | grep -q 'inet.*addr:'
+			then
+				export DEVICE="$dev"
+				break
+			fi
+		done
+	else
+		for interface in ${DEVICE}; do
+			ipconfig -t "$ETHDEV_TIMEOUT" ${interface} | tee /netboot-${interface}.config
+
+			[ -e /run/net-${interface}.conf ] && . /run/net-${interface}.conf
+
+			if [ "$IPV4ADDR" != "0.0.0.0" ]
+			then
+				break
 			fi
 		done
 	fi
 
-	# split args of ethdevice=eth0,eth1 into "eth0 eth1"
-	for device in $(echo $ETHDEVICE | sed 's/,/ /g') ; do
-		devlist="$devlist $device"
-	done
+	for interface in ${DEVICE}
+	do
+		# source relevant ipconfig output
+		OLDHOSTNAME=${HOSTNAME}
 
-	[ -n "$ETHDEV_TIMEOUT" ] || ETHDEV_TIMEOUT=15
-	echo "Using timeout of $ETHDEV_TIMEOUT seconds for network configuration."
+		[ -e /run/net-${interface}.conf ] && . /run/net-${interface}.conf
 
-	# this is tricky (and ugly) because ipconfig sometimes just hangs/runs into
-	# an endless loop; iff execution fails give it two further tries, that's
-	# why we use '$devlist $devlist $devlist' for the other for loop
-	for dev in $devlist $devlist $devlist ; do
-		echo "Executing ipconfig -t $ETHDEV_TIMEOUT $dev"
-		ipconfig -t "$ETHDEV_TIMEOUT" $dev | tee -a /netboot.config &
-		jobid=$!
-		sleep "$ETHDEV_TIMEOUT" ; sleep 1
-		if [ -r /proc/"$jobid"/status ] ; then
-			echo "Killing job $jobid for device $dev as ipconfig ran into recursion..."
-			kill -9 $jobid
-		fi
+		[ -z ${HOSTNAME} ] && HOSTNAME=${OLDHOSTNAME}
+		export HOSTNAME
 
-		# if configuration of device worked we should have an assigned
-		# IP address, iff so let's use the according as $DEVICE for later usage
-		# simple and primitive approach which seems to work fine
-		if ifconfig $dev | grep -q 'inet.*addr:' ; then
-			export DEVICE="$dev"
-			break
-		fi
-	done
-
-	else
-	ipconfig ${DEVICE} | tee /netboot.config
-	fi
-
-	# source relevant ipconfig output
-	OLDHOSTNAME=${HOSTNAME}
-	. /tmp/net-${DEVICE}.conf
-	[ -z ${HOSTNAME} ] && HOSTNAME=${OLDHOSTNAME}
-	export HOSTNAME
-
-	if [ -n "${DEVICE}" ]
-	then
-		HWADDR="$(cat /sys/class/net/${DEVICE}/address)"
-	fi
-
-	if [ ! -e "/etc/resolv.conf" ]
-	then
-		echo "Creating /etc/resolv.conf"
-
-		if [ -n "${DNSDOMAIN}" ]
+		if [ -n "${interface}" ]
 		then
-			echo "domain ${DNSDOMAIN}" > /etc/resolv.conf
-			echo "search ${DNSDOMAIN}" > /etc/resolv.conf
+			HWADDR="$(cat /sys/class/net/${interface}/address)"
 		fi
 
-		for i in ${IPV4DNS0} ${IPV4DNS1} ${IPV4DNS1}
-		do
-			echo "nameserver $i" >> /etc/resolv.conf
-		done
-	fi
+		if [ ! -e "/etc/resolv.conf" ]
+		then
+			echo "Creating /etc/resolv.conf"
 
-	# Check if we have a network device at all
-	if ! ls /sys/class/net/"$DEVICE" > /dev/null 2>&1 && \
-	   ! ls /sys/class/net/eth0 > /dev/null 2>&1 && \
-	   ! ls /sys/class/net/wlan0 > /dev/null 2>&1 && \
-	   ! ls /sys/class/net/ath0 > /dev/null 2>&1 && \
-	   ! ls /sys/class/net/ra0 > /dev/null 2>&1
-	then
-		panic "No supported network device found, maybe a non-mainline driver is required."
-	fi
+			if [ -n "${DNSDOMAIN}" ]
+			then
+				echo "domain ${DNSDOMAIN}" > /etc/resolv.conf
+				echo "search ${DNSDOMAIN}" >> /etc/resolv.conf
+			fi
+
+			for i in ${IPV4DNS0} ${IPV4DNS1} ${IPV4DNS1}
+			do
+				if [ -n "$i" ] && [ "$i" != 0.0.0.0 ]
+				then
+					echo "nameserver $i" >> /etc/resolv.conf
+				fi
+			done
+		fi
+
+		# Check if we have a network device at all
+		if ! ls /sys/class/net/"$interface" > /dev/null 2>&1 && \
+		   ! ls /sys/class/net/eth0 > /dev/null 2>&1 && \
+		   ! ls /sys/class/net/wlan0 > /dev/null 2>&1 && \
+		   ! ls /sys/class/net/ath0 > /dev/null 2>&1 && \
+		   ! ls /sys/class/net/ra0 > /dev/null 2>&1
+		then
+			panic "No supported network device found, maybe a non-mainline driver is required."
+		fi
+	done
 }
 
 do_netmount()
